# Form implementation generated from reading ui file '.\ui_main.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1066, 641)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Main)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalFrame = QtWidgets.QFrame(parent=Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolBox = QtWidgets.QFrame(parent=self.verticalFrame)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 50))
        self.toolBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.toolBox.setObjectName("toolBox")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.toolBox)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.addButton = QtWidgets.QPushButton(parent=self.toolBox)
        self.addButton.setMinimumSize(QtCore.QSize(150, 20))
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_13.addWidget(self.addButton)
        self.fisheyeButton = QtWidgets.QPushButton(parent=self.toolBox)
        self.fisheyeButton.setMinimumSize(QtCore.QSize(150, 20))
        self.fisheyeButton.setObjectName("fisheyeButton")
        self.horizontalLayout_13.addWidget(self.fisheyeButton)
        self.parameterButton = QtWidgets.QPushButton(parent=self.toolBox)
        self.parameterButton.setMinimumSize(QtCore.QSize(150, 20))
        self.parameterButton.setObjectName("parameterButton")
        self.horizontalLayout_13.addWidget(self.parameterButton)
        self.line = QtWidgets.QFrame(parent=self.toolBox)
        self.line.setMaximumSize(QtCore.QSize(16777215, 100))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_13.addWidget(self.line)
        self.recordedButton = QtWidgets.QPushButton(parent=self.toolBox)
        self.recordedButton.setMinimumSize(QtCore.QSize(150, 20))
        self.recordedButton.setObjectName("recordedButton")
        self.horizontalLayout_13.addWidget(self.recordedButton)
        self.capturedButton = QtWidgets.QPushButton(parent=self.toolBox)
        self.capturedButton.setMinimumSize(QtCore.QSize(150, 20))
        self.capturedButton.setObjectName("capturedButton")
        self.horizontalLayout_13.addWidget(self.capturedButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.toolBox)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.verticalFrame)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1044, 562))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.verticalFrame)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Form"))
        self.addButton.setText(_translate("Main", "Add"))
        self.fisheyeButton.setText(_translate("Main", "Fisheye"))
        self.parameterButton.setText(_translate("Main", "Parameter"))
        self.recordedButton.setText(_translate("Main", "Recorded"))
        self.capturedButton.setText(_translate("Main", "Captured"))
