# Form implementation generated from reading ui file '.\ui_tile.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Tile(object):
    def setupUi(self, Tile):
        Tile.setObjectName("Tile")
        Tile.resize(526, 341)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Tile)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.videoLabel = QtWidgets.QLabel(parent=Tile)
        self.videoLabel.setMinimumSize(QtCore.QSize(300, 260))
        self.videoLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.videoLabel.setText("")
        self.videoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.videoLabel.setObjectName("videoLabel")
        self.verticalLayout.addWidget(self.videoLabel)
        self.frame = QtWidgets.QFrame(parent=Tile)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.setupButton = QtWidgets.QPushButton(parent=self.frame)
        self.setupButton.setMinimumSize(QtCore.QSize(0, 20))
        self.setupButton.setObjectName("setupButton")
        self.horizontalLayout_3.addWidget(self.setupButton)
        self.captureButton = QtWidgets.QPushButton(parent=self.frame)
        self.captureButton.setMinimumSize(QtCore.QSize(0, 20))
        self.captureButton.setObjectName("captureButton")
        self.horizontalLayout_3.addWidget(self.captureButton)
        self.recordButton = QtWidgets.QPushButton(parent=self.frame)
        self.recordButton.setMinimumSize(QtCore.QSize(0, 20))
        self.recordButton.setObjectName("recordButton")
        self.horizontalLayout_3.addWidget(self.recordButton)
        self.timeStartLabel = QtWidgets.QLabel(parent=self.frame)
        self.timeStartLabel.setScaledContents(False)
        self.timeStartLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.timeStartLabel.setObjectName("timeStartLabel")
        self.horizontalLayout_3.addWidget(self.timeStartLabel)
        self.horizontalSlider = QtWidgets.QSlider(parent=self.frame)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(100, 0))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_3.addWidget(self.horizontalSlider)
        self.timeEndLabel = QtWidgets.QLabel(parent=self.frame)
        self.timeEndLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.timeEndLabel.setObjectName("timeEndLabel")
        self.horizontalLayout_3.addWidget(self.timeEndLabel)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Tile)
        QtCore.QMetaObject.connectSlotsByName(Tile)

    def retranslateUi(self, Tile):
        _translate = QtCore.QCoreApplication.translate
        Tile.setWindowTitle(_translate("Tile", "Form"))
        self.setupButton.setText(_translate("Tile", "Setup"))
        self.captureButton.setText(_translate("Tile", "Capture"))
        self.recordButton.setText(_translate("Tile", "Record"))
        self.timeStartLabel.setText(_translate("Tile", "00:00"))
        self.timeEndLabel.setText(_translate("Tile", "99:99"))
